[supervisord]
nodaemon=true
logfile=/app/logs/supervisord.log

[program:fastapi]
command=python main.py
directory=/app
autostart=true
autorestart=true

[program:whatsapp]
command=node whatsapp/whatsapp_bravo.js
directory=/app
autostart=false
autorestart=false
environment=PUPPETEER_EXECUTABLE_PATH="/usr/bin/chromium"
